baseURL: "https://hsuching.com/" 
title: 文化、教育與法律札記
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: 研究主題
          url: topics/
          weight: 1 
        - name: 憲身說法
          url: podcast/
          weight: 2
        - name: 參與討論
          url: discussion/
          weight: 3
        - name: 關於
          url: about/
          weight: 4 


params:
    description: "給教師、學生與研究者的文化法、教育法、人權教育與法治教育的知識札記"
    author: 徐筱菁
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["topics","podcast"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: 徐筱菁｜文化、教育與法律札記
          subtitle: "Notes on Culture, Education & Law"
          imageUrl: "picture.png"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: 研究主題
              url: topics/
            - name: 憲身說法
              url: podcast/


          socialIcons:
            - name: Email
              url: mailto:hsu.cc@mail.ntue.edu.tw        

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "徐筱菁"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2